import React from "react";
import Head from "next/head";
import Link from "next/link";
import Navbar from "@/components/Navbar";

const LandingPage = () => {
  return (
    <>
      <Head>
        <title>Get Menu!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section
        className="min-h-screen flex flex-col justify-center items-center text-white relative"
        style={{ backgroundImage: 'url("/LandingPageImage.jpg")' }}
      >
        <Navbar />
        <div className="absolute inset-0 bg-black opacity-50"></div>
        <div className="relative z-10 text-center">
          <h1 className="text-5xl mb-4">Welcome to Eats & Treats!</h1>
          <h3 className="text-3xl mb-4">Great Food, Good Mood</h3>
          <h4 className="text-2xl mb-4">
            "A world of flavors awaits, where every bite tells a story. Dive
            into a realm of exquisite tastes, and let your senses wander."
          </h4>
          <Link href="/food">
            <button className="px-6 py-3 bg-[#6A1E55] rounded-md text-xl hover:bg-[#A64D79]">
              Click to See our Menu List!
            </button>
          </Link>
        </div>
      </section>
    </>
  );
};

export default LandingPage;
